import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuComponent from "./components/MenuComponent";
import MainLayout from "./components/MainLayout";

const inter = Inter({ subsets: ["latin"] });

import localFont from '@next/font/local'
import { use } from "react";

const helvetica = localFont({
  src: [
    {
      path: './assets/fonts/HelveticaNeue-Thin.ttf',
      weight: '100'
    },
    {
      path: './assets/fonts/HelveticaNeue.ttf',
      weight: '400'
    },
    {
      path: './assets/fonts/HelveticaNeue-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-helvetica'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.variable}><MainLayout>
      {children}</MainLayout></body>
    </html>
  );
}
